// Code generated by sync-pro.mjs. DO NOT EDIT.
package main

import (
	_ "noyo/plugins/platform/aiot"
	_ "noyo/plugins/platform/mqtt_api"
	_ "noyo/plugins/platform/sagoo"
	_ "noyo/plugins/protocol/bacnet"
	_ "noyo/plugins/protocol/modbus"
)
