// Code generated by sync-pro.mjs. DO NOT EDIT.
package main

import (
	_ "noyo/plugins/pro/platform/ai_copilot"
	_ "noyo/plugins/pro/platform/ai_predict"
	_ "noyo/plugins/pro/platform/license_auth"
	_ "noyo/plugins/pro/protocol/gb28181"
	_ "noyo/plugins/pro/protocol/script"
)
