import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rootDir = path.resolve(__dirname, '..');
const proDir = path.resolve(rootDir, '../noyo-pro');

const requestedEdition = process.env.NOYO_EDITION;
let hasPro = false;

if (requestedEdition === 'community') {
    console.log('[Sync-Pro] Forced community edition.');
    hasPro = false;
} else if (requestedEdition === 'pro') {
    if (!fs.existsSync(proDir)) {
        console.error(`[Sync-Pro] Error: Pro edition requested but ${proDir} not found!`);
        process.exit(1);
    }
    hasPro = true;
} else {
    hasPro = fs.existsSync(proDir);
}

console.log(`[Sync-Pro] Checking for noyo-pro at ${proDir}... ${fs.existsSync(proDir) ? 'Found' : 'Not found'}, Active Edition: ${hasPro ? 'Pro' : 'Community'}`);

// 1. Handle Backend Plugins
const backendBasePluginsDir = path.join(rootDir, 'backend/plugins');
const backendProPluginsDir = path.join(proDir, 'backend/plugins');
const backendProLinkDir = path.join(backendBasePluginsDir, 'pro');
const backendProImportsFile = path.join(rootDir, 'backend/pro_imports.go');

// 2. Handle Frontend Plugins
const frontendBasePluginsDir = path.join(rootDir, 'frontend/src/plugins');
const frontendProPluginsDir = path.join(proDir, 'frontend/src/plugins');
const frontendProLinkDir = path.join(frontendBasePluginsDir, 'pro');

function syncSymlink(target, linkPath) {
    if (fs.existsSync(linkPath)) {
        try {
            fs.unlinkSync(linkPath);
        } catch(e) {
            try { fs.rmdirSync(linkPath); } catch(err) {}
        }
    }
    if (hasPro && fs.existsSync(target)) {
        try {
            fs.symlinkSync(target, linkPath, 'junction');
            console.log(`[Sync-Pro] Created junction ${linkPath} -> ${target}`);
        } catch(e) {
            console.error(`[Sync-Pro] Failed to create junction for ${linkPath}:`, e.message);
        }
    }
}

// Ensure base directories exist
if (!fs.existsSync(backendBasePluginsDir)) fs.mkdirSync(backendBasePluginsDir, { recursive: true });
if (!fs.existsSync(frontendBasePluginsDir)) fs.mkdirSync(frontendBasePluginsDir, { recursive: true });

// Sync Directories
syncSymlink(backendProPluginsDir, backendProLinkDir);
syncSymlink(frontendProPluginsDir, frontendProLinkDir);

// Generate backend/pro_imports.go
if (hasPro) {
    let imports = [];
    const collectGoPlugins = (dir, prefix) => {
        if (!fs.existsSync(dir)) return;
        const items = fs.readdirSync(dir);
        for (const item of items) {
            const itemPath = path.join(dir, item);
            if (fs.statSync(itemPath).isDirectory()) {
                const pluginGoPath = path.join(itemPath, 'plugin.go');
                if (fs.existsSync(pluginGoPath)) {
                    imports.push(`_ "noyo/plugins/pro/${prefix}${item}"`);
                } else {
                    collectGoPlugins(itemPath, `${prefix}${item}/`);
                }
            }
        }
    };
    collectGoPlugins(backendProPluginsDir, '');

    const importLines = imports.join('\n\t');
    const goContent = `// Code generated by sync-pro.mjs. DO NOT EDIT.
package main

import (
\t${importLines}
)
`;
    fs.writeFileSync(backendProImportsFile, goContent, 'utf-8');
    console.log(`[Sync-Pro] Generated backend/pro_imports.go with ${imports.length} plugins.`);
} else {
    if (fs.existsSync(backendProImportsFile)) {
        fs.unlinkSync(backendProImportsFile);
        console.log(`[Sync-Pro] Removed backend/pro_imports.go`);
    }
}

// Generate backend/community_imports.go
const backendCommunityImportsFile = path.join(rootDir, 'backend/community_imports.go');
let communityImports = [];
const collectCommunityGoPlugins = (dir, prefix) => {
    if (!fs.existsSync(dir)) return;
    const items = fs.readdirSync(dir);
    for (const item of items) {
        if (prefix === '' && item === 'pro') continue; // Skip pro directory
        if (item.startsWith('.')) continue; // Skip hidden files and broken symlinks like .pro

        const itemPath = path.join(dir, item);
        try {
            if (fs.statSync(itemPath).isDirectory()) {
                const pluginGoPath = path.join(itemPath, 'plugin.go');
                if (fs.existsSync(pluginGoPath)) {
                    communityImports.push(`_ "noyo/plugins/${prefix}${item}"`);
                } else {
                    collectCommunityGoPlugins(itemPath, `${prefix}${item}/`);
                }
            }
        } catch (e) {
            console.warn(`[Sync-Pro] Warning: skipping ${itemPath}: ${e.message}`);
        }
    }
};
collectCommunityGoPlugins(backendBasePluginsDir, '');

if (communityImports.length > 0) {
    const importLines = communityImports.join('\n\t');
    const goContent = `// Code generated by sync-pro.mjs. DO NOT EDIT.
package main

import (
\t${importLines}
)
`;
    fs.writeFileSync(backendCommunityImportsFile, goContent, 'utf-8');
    console.log(`[Sync-Pro] Generated backend/community_imports.go with ${communityImports.length} plugins.`);
} else {
    if (fs.existsSync(backendCommunityImportsFile)) {
        fs.unlinkSync(backendCommunityImportsFile);
        console.log(`[Sync-Pro] Removed backend/community_imports.go`);
    }
}

